services:
  google-sheets-crud:
    image: npcdw/google-sheets-crud:latest
    container_name: google-sheets-crud
    ports:
      - 5234:5234
    volumes:
      - "${PWD}/data/:/google-sheets-crud/"
    environment:
      TZ : 'Asia/Shanghai'
      LANG: 'C.UTF-8'
      LC_ALL: 'C.UTF-8'